# Generated by Django 5.0.4 on 2024-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
