# Generated by Django 5.0.4 on 2024-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_materialrequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='request_date',
            field=models.DateField(),
        ),
    ]
