# Generated by Django 5.0.4 on 2024-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadedmaterialrequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
