# Generated by Django 5.0.4 on 2024-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_materialrequest_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
