# Generated by Django 5.0.4 on 2024-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_material_material_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_id',
            field=models.CharField(default='DEFAULT_ID', max_length=50, unique=True),
        ),
    ]
